SportsStore/SportsStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            repository = repo;


        }
   public PartialViewResult Menu(string category=null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> Categories = repository.Products.Select(x => x.category).Distinct().OrderBy(x => x);
            return PartialView(Categories);
        }
        // GET: Nav
        //public string Menu()
        //{
        //    return " Hello from navigarter";
        //}
    }
}

SportsStore/SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@Model SportsStore.Domain.Entities.Product
<div>
    <h3>
        <strong>@Model.Name</strong>
        <span class=" pull-right label  label-primary "> @Model.Price.ToString("c")</span>

    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {

    <div class="pull-right">
        @Html.HiddenFor(x => x.ProductId)
        @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
        <input type="submit" class="btn btn-success" value="Add To Cart" />
    </div>
    }
    <span class="lead">@model.Description </span>

</div>

SportsStore/SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{

    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/validate")
    
    <title></title>
</head>
<body>
    @if (TempData["message"]!=null)
    {
    <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody();
</body>
</html>

SportsStore/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>

            </div>
        </div>*@
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <a class="navbar-brand" href="#">Sports Store</a>
        @Html.Action("Summary", "Cart")
    </div>

    <div class=" row panel">
        <div id="categories" class="col-xs-3">

            @Html.Action("Menu", "Nav")
            @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>*@
        </div>

        <div class="container body-content col-xs-8">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application  </p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SportsStore/SportsStore.WebUI/Views/Shared/_PartialView.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>
            @Model.Name
        </strong>
        <span class="pull-right label-primary">  @Model.Price.ToString("c")</span>
        <span class="lead">@Model.Description </span>
        <span class="lead">@Model.Description </span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div >
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add To Cart" />
        </div>
    }

    @*@using (Html.BeginForm("AddToCart", "Cart"))
        {

            <div class="pull-right">
                @Html.HiddenFor(x => x.ProductId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Add To Cart" />
            </div>
        }
        <span class="lead">@model.Description </ span >*@

</div>